config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/statistics/overall?isp=all')

  namespace :api do
    namespace :v1 do
      namespace :chart do
        resources :raw_data, only: %i[index]
        resources :rolling_averages, only: %i[index]
        resources :time_of_day, only: %i[index]
        resources :measurement_server_performance, only: %i[index]
      end
      resources :measurements, only: %i[create]
    end
  end

  namespace :statistics do
    get 'overall', to: 'overall#index'
    get 'measurement_servers', to: 'measurement_servers#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Internet monitor</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="<%= statistics_overall_url(isp: 'all')%>">Internet monitor</a>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <%= nav_link 'Overall statistics', statistics_overall_url(isp: 'all') %>
            <%= nav_link 'Measurement server performance', statistics_measurement_servers_url %>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Filter Overall statistics by ISP</span>
            </h6>
            <% available_isps.each do |isp| %>
            <%= nav_link isp, statistics_overall_url(isp: isp) %>
            <% end %>
          </ul>
        </div>
      </nav>
      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <%= yield %>
      </main>
    </div>
  </div>
</body>

</html>